project_id = "isurgrecabocqcxocgwg"

[functions.chat]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.yookassa-webhook]
verify_jwt = false
